version: "3"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: api
    links: 
      - database
    depends_on: 
      - database
    environment: 
      - USERNAME=postgres
      - PASSWORD=postgres
      - DATABASE=postgres
      - HOST=database
      - DIALECT=postgres
      - DATABASE_PORT=5432
      - PORT=8080
    ports: 
      - "8080:8080"
  client:
    build: client
    links:
      - api
    depends_on: 
      - api
    ports: 
      - "3000:3000"
    stdin_open: true

volumes:
  pgdata: